apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-eks
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: capi-eks
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: capi-eks
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-control-plane
  namespace: default
spec:
  region: us-west-2
  sshKeyName: default
  version: v1.25
  addons:
    - name: aws-ebs-csi-driver
      version: v1.17.0-eksbuild.1
      conflictResolution: overwrite
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capi-eks-pool-0
  namespace: default
spec:
  clusterName: capi-eks
  replicas: 4
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: capi-eks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: capi-eks-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: capi-eks-pool-0
  namespace: default
spec:
  roleAdditionalPolicies:
    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy