
# Details on checks can be found on this page and the like: https://docs.kubelinter.io/#/generated/checks
checks:
  addAllBuiltIn: true
  exclude:
    - "unset-cpu-requirements" # Not every pod requires this, for example hooks, we can change opinion later
    - "unset-memory-requirements" # Not every pod requires this, for example hooks, we can change opinion later
    - "no-read-only-root-fs" # Some volume mounts require writes
    - "required-annotation-email" # Not a requirement for out deployments
    - "no-node-affinity" # Not every pod requires this
