version: '3'

# NOTE: Task doesn't allow to override environment variables. Thus, when an
# environment variable is referenced in a taskfile, it is because we expect it
# to be defined by the environment where Task is being invoked or in a task's
# `env:` attribute.
dotenv: []

vars:
  BINDIR: .local/bin

  # Configuration Defaults
  NAMESPACE: rn
  RELEASE: rp
  KIND_CLUSTERNAME: rp-helm
  CLUSTER_NAME: '{{.CLUSTER_NAME | default "capi"}}'
  CLUSTER_NAMESPACE: '{{.CLUSTER_NAMESPACE | default "default"}}'

  # Overridable task vars
  HELM_OPTIONS: ""
  KIND_FLAGS: "--config .github/kind.yaml"

  SRC_DIR:
    sh: realpath {{default "." .SRC_DIR}}

# if a task is referenced multiple times, only run it once
run: once


# Try to follow "THING:ACTION:SPECIFIER" for specific actions.
# Examples:
# - chart:lint:redpanda # Lint the redpanda chart
# - helm:add-repo:jetstack # Add the jetstack repo to helm
# - helm:install:cert-manager # Install cert-manager using helm
# When this files becomes too long, all of THING can be extracted into it's own
# file.
# For CI or running many types of similar ACTIONs, have a top level task named
# just ACTION. For example, "lint" would run tasks that match *:lint:*. (Though
# there's no matching in taskile AFAIK so this is done by hand).
#
# Feel free to change this format provided there's a general flow to the new
# format, all existing tasks are changed, and backwards compatibility is
# maintained via aliases.
tasks:

  shell:
    desc: "Launch a development shell"
    cmds:
      - nix develop --impure

  ci:lint:
    cmds:
      - task: generate
      - gofumpt -w .
      # Fail on any generated diffs.
      - git diff --exit-code
      # Actually run linters.
      - actionlint
      - ct lint --chart-dirs ./charts --check-version-increment=false --github-groups --all
      - .github/check-ci-files.sh charts/connectors/ci
      - .github/check-ci-files.sh charts/kminion/ci
      - .github/check-ci-files.sh charts/operator/ci
      - .github/check-ci-files.sh charts/redpanda/ci

  generate:
    desc: "Run all file generation tasks"
    cmds:
      # Generate chart README.md's
      - nix develop -c helm-docs -c ./charts/
      # Ensure go deps are up to date
      - go mod tidy
      # Ensure flake.nix has been formatted.
      - nix fmt

  helm:add-repo:jetstack:
    aliases:
      - add-jetstack-repo
    cmds:
      - helm repo add jetstack https://charts.jetstack.io
      - helm repo update
    status:
      - helm search repo -r '\vjetstack/cert-manager\v' | grep cert-manager

  helm:add-repo:prometheus-community:
    aliases:
      - add-prometheus-community-repo
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo update
    status:
      - helm search repo -r '\vprometheus-community/kube-prometheus-stack\v' | grep metallb

  helm:add-repo:metallb:
    aliases:
      - add-metallb-repo
    cmds:
      - helm repo add metallb https://metallb.github.io/metallb
      - helm repo update
    status:
      - helm search repo -r '\vmetallb/metallb\v' | grep metallb

  helm:install:metallb:
    aliases:
      - install-metallb
    deps:
      - helm:add-repo:metallb
    cmds:
      - |
        helm install metallb metallb/metallb \
        --create-namespace \
        --namespace metallb-system \
        --version 0.13.10 \
        --wait \
        --wait-for-jobs
      - kubectl --namespace metallb-system apply -f .github/metallb-config.yaml

  helm:install:cert-manager:
    aliases:
      - install-cert-manager
    deps:
      - helm:add-repo:jetstack
    cmds:
      - |
        helm install cert-manager jetstack/cert-manager \
        --create-namespace \
        --namespace cert-manager \
        --set installCRDs=true \
        --version v1.12.16 \
        --wait \
        --wait-for-jobs

  helm:install:kube-prometheus-stack:
    aliases:
      - install-kube-prometheus-stack
    deps:
      - helm:add-repo:prometheus-community
    cmds:
      - |
        helm install prometheus prometheus-community/kube-prometheus-stack \
        --namespace prometheus \
        --create-namespace \
        --set alertmanager.enabled=false \
        --set grafana.enabled=false \
        --set kubeStateMetrics.enabled=false \
        --set nodeExporter.enabled=false \
        --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
        --wait \
        --wait-for-jobs

  kind-create:
    cmds:
      - kind create cluster --name {{.KIND_CLUSTERNAME}} {{.KIND_FLAGS}}
      - task: install-cert-manager
      - task: install-metallb
      - task: install-kube-prometheus-stack
    status:
      - "kind get clusters | grep {{.KIND_CLUSTERNAME}}"

  kind-delete:
    cmds:
      - kind delete cluster --name {{.KIND_CLUSTERNAME}}

  sync:charts:
    cmds:
    - task: sync:redpanda:chart
    - task: sync:operator:chart
    - task: sync:connectors:chart
    - task: sync:operator:chart

  sync:redpanda:chart:
    - task: sync:chart
      vars:
        REF: charts/redpanda/v25.1.1-beta1
        LOCAL_DIR: charts/redpanda
        REMOTE_DIR: charts/redpanda

  sync:connectors:chart:
    - task: sync:chart
      vars:
        REF: charts/redpanda/v5.9.21 # No recent release of connectors so pinning to this just because.
        LOCAL_DIR: charts/connectors
        REMOTE_DIR: charts/connectors

  sync:operator:chart:
    - task: sync:chart
      vars:
        REF: operator/v25.1.1-beta2
        LOCAL_DIR: charts/operator
        REMOTE_DIR: operator/chart

  sync:console:chart:
    - task: sync:chart
      vars:
        REF: charts/console/v3.1.0
        LOCAL_DIR: charts/console
        REMOTE_DIR: charts/console

  sync:chart:
    internal: true
    vars:
      REF: '{{ .REF }}'
      LOCAL_DIR: '{{ .LOCAL_DIR }}'
      REMOTE_DIR: '{{ .REMOTE_DIR }}'
    required: [REF, LOCAL_DIR, REMOTE_DIR]
    run: when_changed
    label: 'sync:chart:{{ .LOCAL_DIR }}'
    cmds:
      - rm -rf '{{ .SRC_DIR }}/{{ .LOCAL_DIR }}'
      - mkdir -p '{{ .SRC_DIR }}/{{ .LOCAL_DIR }}'
      - |
        cd {{ .LOCAL_DIR }} && \
        curl -Lo - 'https://github.com/redpanda-data/redpanda-operator/archive/{{ .REF }}.tar.gz' | \
        tar \
          --gunzip \
          --extract \
          --wildcards \
          --exclude '*.go' \
          --exclude 'go.mod' \
          --exclude 'go.sum' \
          --exclude '*.txtar' \
          --exclude '.changes' \
          --strip-components {{ (.REMOTE_DIR | split "/" | len) | add 1 }} \
          '*/{{ .REMOTE_DIR }}'
