//go:build !generate

// +gotohelm:ignore=true
//
// Code generated by genpartial DO NOT EDIT.
package main

import (
	alias2 "bytes"
	alias1 "os"
)

type PartialExampleStruct struct {
	A1 PartialMapGeneric[int]                            "json:\",omitempty\""
	A2 PartialMapGeneric[PartialNestedStruct]            "json:\",omitempty\""
	A3 PartialMapGeneric[*PartialNestedStruct]           "json:\",omitempty\""
	A4 PartialMapGeneric[IntAlias]                       "json:\",omitempty\""
	A5 PartialMapGeneric[PartialMapGeneric[IntAlias]]    "json:\",omitempty\""
	A6 PartialMapGeneric[PartialMapGeneric[alias1.File]] "json:\",omitempty\""
	A7 PartialMapGeneric[PartialMapGeneric[fs.FileInfo]] "json:\",omitempty\""
	A8 *PartialGenericStruct[string]                     "json:\",omitempty\""
	A9 *PartialGenericStruct[PartialGenericStruct[*int]] "json:\",omitempty\""
	B1 *int                                              "json:\",omitempty\""
	B2 *int                                              "json:\",omitempty\""
	C1 *struct {
		Any any  "json:\",omitempty\""
		Int *int "json:\",omitempty\""
	} "json:\",omitempty\""
	C2 *struct{}            "json:\",omitempty\""
	D1 *PartialNestedStruct "json:\",omitempty\""
	D2 *PartialNestedStruct "json:\",omitempty\""
	E1 []any                "json:\",omitempty\""
	E2 []int                "json:\",omitempty\""
	E3 []*int               "json:\",omitempty\""
	E4 []map[string]struct {
		Foo *string "json:\",omitempty\""
	} "json:\",omitempty\""
	E5 []map[string]PartialNestedStruct                       "json:\",omitempty\""
	E6 []map[string]PartialGenericStruct[PartialNestedStruct] "json:\",omitempty\""
	F1 []*int                                                 "json:\"L,omitempty\""
	F2 *string                                                "yaml:\"M\" json:\",omitempty\""
	F3 *IntAlias                                              "json:\",omitempty\""
	G1 *alias2.Buffer                                         "json:\",omitempty\""
	G2 *alias1.File                                           "json:\",omitempty\""
	G3 *alias2.Reader                                         "json:\",omitempty\""
	H1 map[string]any                                         "json:\",omitempty\""
	H2 map[string]PartialNestedStruct                         "json:\",omitempty\""
	H3 map[string]PartialGenericStruct[int]                   "json:\",omitempty\""
	H4 map[string]PartialGenericStruct[PartialNestedStruct]   "json:\",omitempty\""
	H5 PartialMapAlias                                        "json:\",omitempty\""
}

type PartialNestedStruct struct {
	Map map[string]string "json:\",omitempty\""
}

type PartialMapAlias map[string]int

type PartialMapGeneric[T any] map[string]T

type PartialGenericStruct[T any] struct {
	Foo T "json:\",omitempty\""
}
