{{- if eq (include "tls-enabled" .) "true" }}
  {{- $release := .Release }}
  {{- $values := .Values }}
  {{- range $name, $issuer := $values.auth.tls.certs }}
    {{- $d := $issuer.duration }}
apiVersion: v1
data:
  password: changeme
kind: Secret
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert-keystore
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
spec:
  dnsNames:
  - {{ template "redpanda.fullname" $ }}-cluster.{{ (include "redpanda.internal.domain" $) | trimSuffix "." }}
  - '*.{{ template "redpanda.fullname" $ }}-cluster.{{ (include "redpanda.internal.domain" $) | trimSuffix "." }}'
  - {{ (include "redpanda.internal.domain" $) | trimSuffix "." }}
  - '*.{{ (include "redpanda.internal.domain" $) | trimSuffix "." }}'
  - {{ (first $values.config.redpanda.kafka_api).external.subdomain }}
  - {{ printf "*.%s" (first $values.config.redpanda.kafka_api).external.subdomain | squote }}
  duration: {{ $d | default "43800h" }}
  isCA: false
  commonName: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  secretName: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ template "redpanda.fullname" $ }}-{{ $name }}-root-issuer
    kind: Issuer
    group: cert-manager.io
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert-keystore
---
  {{- end }}
{{- end }}
