{{/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "redpanda.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "redpanda.chart" . }}
    app.kubernetes.io/name: {{ template "redpanda.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: {{ template "redpanda.name" . }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "redpanda.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ template "redpanda.fullname" . }}
  replicas: {{ .Values.statefulset.replicas | int64 }}
  updateStrategy: {{- toYaml .Values.statefulset.updateStrategy | nindent 4 }}
  podManagementPolicy: {{ .Values.statefulset.podManagementPolicy | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "redpanda.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: {{ template "redpanda.name" . }}
      {{- with .Values.labels }}
  {{- toYaml . | nindent 8 }}
{{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- with $.Values.statefulset.annotations }}
  {{- toYaml . | nindent 8 }}
{{- end }}
{{- toYaml .Values.statefulset.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ template "redpanda.name" . }}-configurator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/sh", "-c"]
          env:
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - >
              CONFIG=/etc/redpanda/redpanda.yaml;
              NODE_ID=${SERVICE_NAME##*-};
              cp /tmp/base-config/redpanda.yaml "$CONFIG";
              rpk --config "$CONFIG" config set redpanda.node_id $NODE_ID;
              if [ "$NODE_ID" = "0" ]; then
                rpk --config "$CONFIG" config set redpanda.seed_servers '[]' --format yaml;
              fi;
          volumeMounts:
            - name: {{ template "redpanda.fullname" . }}
              mountPath: /tmp/base-config
            - name: config
              mountPath: /etc/redpanda
          resources:
{{- toYaml .Values.statefulset.resources | nindent 12 }}
{{- toYaml .Values.statefulset.resources | nindent 12 }}
        - name: {{ template "redpanda.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          args:
            - >
              redpanda
              start
              --smp={{ .Values.statefulset.resources.limits.cpu }}
              --memory={{ .Values.statefulset.redpanda.memory }}
              --reserve-memory={{ .Values.statefulset.redpanda.reservedMemory }}
              {{- if (first .Values.config.redpanda.kafka_api).external.enabled }}
              --advertise-kafka-addr=kafka://{{ template "redpanda.kafka.internal.advertise.address" . }}:{{ template "redpanda.kafka.internal.advertise.port" . }},external://{{ template "redpanda.kafka.external.advertise.address" . }}:{{ template "redpanda.kafka.external.advertise.nodeport.port" . }},
              --kafka-addr=kafka://{{ template "redpanda.kafka.internal.listen.address" . }}:{{ template "redpanda.kafka.internal.listen.port" . }},external://{{ template "redpanda.kafka.external.listen.address" . }}:{{ template "redpanda.kafka.external.listen.port" . }},
              {{- else }}
              --advertise-kafka-addr=kafka://{{ template "redpanda.kafka.internal.advertise.address" . }}:{{ template "redpanda.kafka.internal.advertise.port" . }}
              --kafka-addr=kafka://{{ template "redpanda.kafka.internal.listen.address" . }}:{{ template "redpanda.kafka.internal.listen.port" . }}
              {{- end }}
              --advertise-rpc-addr={{ template "redpanda.rpc.advertise.address" . }}:{{ template "redpanda.rpc.advertise.port" . }}
              --rpc-addr={{ template "redpanda.rpc.listen.address" . }}:{{ template "redpanda.rpc.listen.port" . }}
              {{ if (first .Values.config.schema_registry.schema_registry_api).external.enabled }}
              --schema-registry-addr=internal://{{ template "redpanda.schemaregistry.internal.address" . }}:{{ template "redpanda.schemaregistry.internal.port" . }},external://{{ template "redpanda.schemaregistry.external.nodeport.address" . }}:{{ template "redpanda.schemaregistry.external.port" . }}
              {{- else }}
              --schema-registry-addr=internal://{{ template "redpanda.schemaregistry.internal.address" . }}:{{ template "redpanda.schemaregistry.internal.port" . }}
              {{ end }}
              {{- if (first .Values.config.pandaproxy.pandaproxy_api).external.enabled }}
              --advertise-pandaproxy-addr=internal://{{ template "redpanda.pandaproxy.internal.advertise.address" . }}:{{ template "redpanda.pandaproxy.internal.advertise.port" . }},external://{{ template "redpanda.pandaproxy.external.advertise.nodeport.address" . }}:{{ template "redpanda.pandaproxy.external.advertise.nodeport.port" . }}
              --pandaproxy-addr=internal://{{ template "redpanda.pandaproxy.internal.listen.address" . }}:{{ template "redpanda.pandaproxy.internal.listen.port" . }},external://{{ template "redpanda.pandaproxy.external.listen.address" . }}:{{ template "redpanda.pandaproxy.external.listen.port" . }}
              {{- else }}
              --advertise-pandaproxy-addr=internal://{{ template "redpanda.pandaproxy.internal.advertise.address" . }}:{{ template "redpanda.pandaproxy.internal.advertise.port" . }}
              --pandaproxy-addr=internal://{{ template "redpanda.pandaproxy.internal.listen.address" . }}:{{ template "redpanda.pandaproxy.internal.listen.port" . }}
              {{- end }}
              --default-log-level={{ .Values.config.seastar.default_log_level }}
          ports:
            - containerPort: {{ .Values.config.redpanda.admin.port }}
              name: admin
            - containerPort: {{ template "redpanda.kafka.internal.listen.port" . }}
              name: kafka-internal
              {{- if not (empty .Values.loadBalancer) }}
              {{- if .Values.loadBalancer.enabled }}
            - containerPort: {{ template "redpanda.kafka.external.listen.port" . }}
              name: kafka-external
              {{- end }}
              {{- end }}
              {{- if .Values.config.pandaproxy.enabled }}
            - containerPort: {{ template "redpanda.pandaproxy.internal.listen.port" . }}
              name: pandaproxy
              {{- end }}
            - containerPort: {{ template "redpanda.rpc.listen.port" $ }}
              name: rpc
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/redpanda/data
            - name: config
              mountPath: /etc/redpanda
{{- $anyTLS := or (default false .Values.config.redpanda.kafka_api_tls) (default false .Values.config.redpanda.admin_api_tls) (default false .Values.config.redpanda.schema_registry_api_tls) (default false .Values.config.redpanda.pandaproxy_api_tls) -}}
{{- if $anyTLS }}
{{- if .Values.customCerts }}
  {{- range $i, $cert := .Values.customCerts }}
            - name: tls-{{ $cert.name }}
              mountPath: {{ $cert.path | default (printf "/etc/tls/certs/%s" $cert.name) }}
  {{end}}
{{ else }}
            - name: tlscert
              mountPath: /etc/tls/certs
            - name: tlsadmincert
              mountPath: /etc/tls/certs/admin
            - name: tlspandaproxycert
              mountPath: /etc/tls/certs/pandaproxy
            - name: tlsschemaregistrycert
              mountPath: /etc/tls/certs/schema-registry
{{- end }}
{{- end }}
          resources:
{{- toYaml .Values.statefulset.resources | nindent 12 }}
{{- toYaml .Values.statefulset.resources | nindent 12 }}
        - name: datadir
{{- if .Values.storage.persistentVolume.enabled }}
{{- if .Values.storage.persistentVolume.enabled }}
            claimName: datadir
{{- else if .Values.storage.hostPath }}
{{- else if .Values.storage.hostPath }}
            path: {{ .Values.storage.hostPath | quote }}
{{- else }}
{{- else }}
{{- end }}
{{- end }}
          configMap:
            name: {{ template "redpanda.fullname" . }}
        - name: config
          emptyDir: {}
{{- if $anyTLS }}
{{- if .Values.customCerts }}
  {{- range $i, $cert := .Values.customCerts }}
        - name: tls-{{ $cert.name }}
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            {{- if $cert.caEnabled }}
    {{- if $cert.caEnabled }}
              path: ca.crt
            {{- end }}
            secretName: {{ template "redpanda.fullname" $ }}-{{ $cert.name }}-cert
  {{end}}
{{ else }}
        - name: tlscert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            - key: ca.crt
              path: ca.crt
            secretName: {{ template "redpanda.fullname" . }}-kafka-cert
        - name: tlsadmincert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            - key: ca.crt
              path: ca.crt
            secretName: {{ template "redpanda.fullname" . }}-admin-cert
        - name: tlspandaproxycert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            - key: ca.crt
              path: ca.crt
            secretName: {{ template "redpanda.fullname" . }}-proxy-cert
        - name: tlsschemaregistrycert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            - key: ca.crt
              path: ca.crt
            secretName: {{ template "redpanda.fullname" . }}-schema-cert
{{- end }}
{{- end }}
      {{- if or .Values.statefulset.nodeAffinity .Values.statefulset.podAffinity .Values.statefulset.podAntiAffinity }}
{{- if or .Values.statefulset.nodeAffinity .Values.statefulset.podAffinity .Values.statefulset.podAntiAffinity }}
      {{- with .Values.statefulset.nodeAffinity }}
  {{- with .Values.statefulset.nodeAffinity }}
      {{- end }}
  {{- end }}
  {{- with .Values.statefulset.podAffinity }}
      {{- end }}
  {{- end }}
  {{- if .Values.statefulset.podAntiAffinity }}
        {{- if .Values.statefulset.podAntiAffinity.type }}
    {{- if .Values.statefulset.podAntiAffinity.type }}
      {{- if eq .Values.statefulset.podAntiAffinity.type "hard" }}
            - topologyKey: {{ .Values.statefulset.podAntiAffinity.topologyKey }}
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "redpanda.name" . }}
                  app.kubernetes.io/instance: {{ .Release.Name | quote }}
        {{- else if eq .Values.statefulset.podAntiAffinity.type "soft" }}
      {{- else if eq .Values.statefulset.podAntiAffinity.type "soft" }}
            - weight: {{ .Values.statefulset.podAntiAffinity.weight | int64 }}
              podAffinityTerm:
                topologyKey: {{ .Values.statefulset.podAntiAffinity.topologyKey }}
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ template "redpanda.name" . }}
                    app.kubernetes.io/instance: {{ .Release.Name | quote }}
      {{- end }}
    {{- else }}
      {{- toYaml .Values.statefulset.podAntiAffinity | nindent 10 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: {{ template "redpanda.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name | quote }}
  {{- with .Values.statefulset.topologySpreadConstraints }}
        maxSkew: {{ .maxSkew }}
        topologyKey: {{ .topologyKey }}
        whenUnsatisfiable: {{ .whenUnsatisfiable }}
  {{- end }}
{{- end }}
{{- with .Values.statefulset.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
{{- end }}
{{- if .Values.statefulset.priorityClassName }}
      priorityClassName: {{ .Values.statefulset.priorityClassName }}
{{- end }}
{{- with .Values.statefulset.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
{{- end }}
{{- if .Values.storage.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels:
          app.kubernetes.io/name: {{ template "redpanda.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name | quote }}
          app.kubernetes.io/component: {{ template "redpanda.name" . }}
  {{- with .Values.storage.persistentVolume.labels }}
    {{- toYaml . | nindent 10 }}
  {{- end }}
  {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 10 }}
  {{- end }}
  {{- with .Values.storage.persistentVolume.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
  {{- end }}
      spec:
        accessModes: ["ReadWriteOnce"]
  {{- if .Values.storage.persistentVolume.storageClass }}
    {{- if (eq "-" .Values.storage.persistentVolume.storageClass) }}
        storageClassName: ""
    {{- else }}
        storageClassName: {{ .Values.storage.persistentVolume.storageClass | quote }}
    {{- end }}
  {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.persistentVolume.size | quote }}
{{- end }}
