---
plugins:
  - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
      json-to-env:
        - json-key: .
          secret-id: sdlc/prod/buildkite/azure_client_secret
        - json-key: .
          secret-id: sdlc/prod/buildkite/gcp_b64encoded_credentials
        - json-key: .
          secret-id: sdlc/prod/buildkite/github_api_token
        - json-key: .
          secret-id: sdlc/prod/buildkite/helmchart_test_account_aws
        - json-key: .
          secret-id: sdlc/prod/buildkite/helmchart_test_project_id
        - json-key: .
          secret-id: sdlc/prod/buildkite/redpanda_sample_license
        - json-key: .
          secret-id: sdlc/prod/buildkite/slack_vbot_token
agents:
  queue: "k8s-builders"
steps:
  - label: ":cloud: test eks cloud storage"
    env:
      CLOUD_PROVIDER: eks
    command: .buildkite/scripts/cloud-test.sh
    artifact_paths:
      - ".local/artifacts/**/*"
    plugins:
      - seek-oss/aws-sm#v2.3.2: *aws-sm-plugin
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: test eks cloud storage failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
  - label: ":cloud: test gke cloud storage"
    env:
      CLOUD_PROVIDER: gke
    command: .buildkite/scripts/cloud-test.sh
    artifact_paths:
      - ".local/artifacts/**/*"
    plugins:
      - seek-oss/aws-sm#v2.3.2: *aws-sm-plugin
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: test gke cloud storage failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
  - label: ":cloud: test aks cloud storage"
    env:
      CLOUD_PROVIDER: aks
    command: .buildkite/scripts/cloud-test.sh
    artifact_paths:
      - ".local/artifacts/**/*"
    plugins:
      - seek-oss/aws-sm#v2.3.2: *aws-sm-plugin
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: test aks cloud storage failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
