{{/*
Copyright 2020 Redpanda Data, Inc.

Use of this software is governed by the Business Source License
included in the file licenses/BSL.md

As of the Change Date specified in that file, in accordance with
the Business Source License, use of this software will be governed
by the Apache License, Version 2.0
*/}}

{{/* 
This is really only used for tests so far
*/}}

{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "redpanda-operator.fullname" . }}-pvc
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "redpanda-operator.fullname" . }}-pvc
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "redpanda-operator.fullname" . }}-pvc
subjects:
  - kind: ServiceAccount
    name: {{ include "redpanda-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
