{{- if .Values.http.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redpanda-connect.fullname" . }}
  labels:
    {{- include "redpanda-connect.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}

  {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "redpanda-connect.selectorLabels" . | nindent 4 }}
{{- end -}}
