---
# Default values for aks-cluster.

# nameOverride: ""
# fullNameOverride: ""

# Make sure to use same Kubernetes version here as building the GCE image
kubernetesVersion: 1.26.3

# Name of the Azure datacenter location. Change this value to your desired location
location: "westus2"

clientID: ""
tenantID: ""

resourceGroup: ""

subscriptionID: ""

controlPlaneReplicas: 1
workerReplicas: 1

clientSecret:
  name: ""
  namespace: ""