---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvcunbinder
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
