---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: legacypermissions
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - delete
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets/status
    verbs:
      - patch
      - update
