---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managed-decommission
rules:
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas
    verbs:
      - get
      - list
      - watch
