---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: managed-decommission
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - pods
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - patch
      - update
