---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-watcher
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - nodes
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas
    verbs:
      - get
      - list
      - watch
