---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-watcher
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - delete
      - get
      - list
      - patch
      - update
