---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sidecar
  namespace: default
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
