---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: v2-manager
rules:
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas/finalizers
      - schemas/finalizers
      - topics/finalizers
      - users/finalizers
    verbs:
      - update
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas/status
      - schemas/status
      - topics/status
      - users/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - schemas
      - topics
      - users
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
