apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "eks-cluster.fullname" . }}
  namespace: {{ .Release.namespace | default "default" }}
  labels: {{ include "eks-cluster.labels" . | nindent 4 }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: {{ include "eks-cluster.fullname" . }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: {{ include "eks-cluster.fullname" . }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: {{ include "eks-cluster.fullname" . }}
  namespace: {{ .Release.namespace | default "default" }}
  labels: {{ include "eks-cluster.labels" . | nindent 4 }}
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: {{ include "eks-cluster.fullname" . }}
  namespace: {{ .Release.namespace | default "default" }}
spec:
  region: us-west-2
  sshKeyName: default
  version: {{ .Values.kubernetesVersion }}
  addons:
    - name: aws-ebs-csi-driver
      version: v1.17.0-eksbuild.1
      conflictResolution: overwrite
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ include "eks-cluster.fullname" . }}-pool-0
  namespace: {{ .Release.namespace | default "default" }}
  labels: {{ include "eks-cluster.labels" . | nindent 4 }}
spec:
  clusterName: {{ include "eks-cluster.fullname" . }}
  replicas: {{ .Values.nodeCount }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ include "eks-cluster.fullname" . }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: {{ include "eks-cluster.fullname" . }}-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: {{ include "eks-cluster.fullname" . }}-pool-0
  namespace: {{ .Release.namespace | default "default" }}
  labels: {{ include "eks-cluster.labels" . | nindent 4 }}
spec:
  roleAdditionalPolicies:
    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
