apiVersion: v2
name: redpanda-operator
description: Redpanda operator helm chart
type: application

# This is the chart version. This is only placeholder that will be set during release process
version: 0.3.1

# This is the version number of the application being deployed. This is only placeholder that
# will be set during release process.
appVersion: v23.1.13

home: https://vectorized.io
sources:
  - https://github.com/redpanda-data/redpanda
maintainers:
  - name: Vectorizedio
    email: support@vectorized.io

dependencies:
- name: kube-prometheus-stack
  condition: monitoring.enabled
  version: 13.13.1
  repository: https://prometheus-community.github.io/helm-charts
