#!/bin/bash

set -xeuo pipefail

# do not run this during the pipeline upload
if [ "$BUILDKITE_LABEL" == ":pipeline:" ]; then
    exit 0
fi

mkdir -p .local/artifacts
eks() {
    cp charts/redpanda/ci/21-eks-tiered-storage-with-creds-values.yaml .local/artifacts/
    support-bundle -o ".local/artifacts/${CLOUD_PROVIDER}-${BUILDKITE_BUILD_NUMBER}" .buildkite/scripts/bundle.yaml
    unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
}

gke() {
    cp charts/redpanda/ci/22-gke-tiered-storage-with-creds-values.yaml .local/artifacts/
    support-bundle -o ".local/artifacts/${CLOUD_PROVIDER}-${BUILDKITE_BUILD_NUMBER}" .buildkite/scripts/bundle.yaml
    unset CI PROJECT_ID TEST_BUCKET TEST_SA_NAME
}

aks() {
    cp charts/redpanda/ci/23-aks-tiered-storage-with-creds-values.yaml .local/artifacts/
    support-bundle -o ".local/artifacts/${CLOUD_PROVIDER}-${BUILDKITE_BUILD_NUMBER}" .buildkite/scripts/bundle.yaml
    unset CI TEST_STORAGE_ACCOUNT TEST_RESOURCE_GROUP
}

$CLOUD_PROVIDER