apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example
spec:
  hostCollectors:
    - hostOS: {}
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        collectorName: all-logs
        name: all-logs