package main

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/invopop/jsonschema"
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	"github.com/redpanda-data/helm-charts/charts/redpanda"
	"github.com/redpanda-data/helm-charts/pkg/valuesutil"
	corev1 "k8s.io/api/core/v1"
)

func Must[T any](value T, err error) T {
	if err != nil {
		panic(err)
	}
	return value
}

func main() {
	r := &jsonschema.Reflector{
		//  These values are set to minimize the diff between the
		// handwritten jsonschema and the generated jsonschema.
		ExpandedStruct: true,
		DoNotReference: true,

		// For backwards compatibility, don't "close" our objects. There are
		// many fields that are not currently represented. Setting this to
		// false, the default and recommended value, will break many existing
		// installs. TestTemplate will catch many of these breakages.
		AllowAdditionalProperties: true,

		// jsonschema, by default, will rely on omitempty flags to determine if
		// a value is required or not. This has too much of an impact on how
		// the underlying JSON is shaped and marshalled/unmarshalled. Instead,
		// rely on explicitly set required tags.
		RequiredFromJSONSchemaTags: true,

		// Builtin Kubernetes types can generate a JSON schema but it's a built
		// difficult to do so as all the information is stored in kubebuilder
		// annotations. For now, we'll hard code any types that need to be
		// enhanced.
		Mapper: func(t reflect.Type) *jsonschema.Schema {
			switch reflect.New(t).Interface().(type) {
			case *corev1.PodFSGroupChangePolicy:
				return &jsonschema.Schema{
					Type: "string",
					Enum: []any{
						corev1.FSGroupChangeOnRootMismatch,
						corev1.FSGroupChangeAlways,
					},
				}
			case monitoringv1.Duration:
				return &jsonschema.Schema{
					Type:    "string",
					Pattern: "^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$",
				}
			default:
				return nil
			}
		},
	}

	schema := r.Reflect(&redpanda.Values{})

	// Leave a note to dissuade any would be manual editors.
	schema.Description = "DO NOT EDIT!. This file was generated by ./cmd/genschema/genschema.go"

	// Because of jsonschema's usage of an ordered map, the key ordering is a
	// bit strange. Round trip through an untyped map[string]any to have go
	// sort the keys alphabetically. (This helps reduce diff churn).
	untyped := Must(valuesutil.UnmarshalInto[any](schema))
	data := Must(json.MarshalIndent(untyped, "", "  "))

	fmt.Printf("%s\n", data)
}
