package main

import (
	"encoding/json"
	"fmt"

	"github.com/invopop/jsonschema"
	"github.com/redpanda-data/helm-charts/charts/redpanda"
	"github.com/redpanda-data/helm-charts/pkg/valuesutil"
)

func Must[T any](value T, err error) T {
	if err != nil {
		panic(err)
	}
	return value
}

func main() {
	r := &jsonschema.Reflector{
		//  These values are set to minimize the diff between the
		// handwritten jsonschema and the generated jsonschema.
		ExpandedStruct: true,
		DoNotReference: true,

		// For backwards compatibility, don't "close" our objects. There are
		// many fields that are not currently represented. Setting this to
		// false, the default and recommended value, will break many existing
		// installs. TestTemplate will catch many of these breakages.
		AllowAdditionalProperties: true,

		// jsonschema, by default, will rely on omitempty flags to determine if
		// a value is required or not. This has too much of an impact on how
		// the underlying JSON is shaped and marshalled/unmarshalled. Instead,
		// rely on explicitly set required tags.
		RequiredFromJSONSchemaTags: true,
	}

	schema := r.Reflect(&redpanda.Values{})

	// Leave a note to dissuade any would be manual editors.
	schema.Description = "DO NOT EDIT!. This file was generated by ./cmd/genschema/genschema.go"

	// Because of jsonschema's usage of an ordered map, the key ordering is a
	// bit strange. Round trip through an untyped map[string]any to have go
	// sort the keys alphabetically. (This helps reduce diff churn).
	untyped := Must(valuesutil.UnmarshalInto[any](schema))
	data := Must(json.MarshalIndent(untyped, "", "  "))

	fmt.Printf("%s\n", data)
}
