package main

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"

	"github.com/invopop/jsonschema"
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	"github.com/redpanda-data/helm-charts/charts/operator"
	"github.com/redpanda-data/helm-charts/charts/redpanda"
	"github.com/redpanda-data/helm-charts/pkg/valuesutil"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/util/intstr"
)

var schemas = map[string]any{
	"redpanda": &redpanda.Values{},
	"operator": &operator.Values{},
}

func Must[T any](value T, err error) T {
	if err != nil {
		panic(err)
	}
	return value
}

func main() {
	r := &jsonschema.Reflector{
		//  These values are set to minimize the diff between the
		// handwritten jsonschema and the generated jsonschema.
		ExpandedStruct: true,
		DoNotReference: true,

		// For backwards compatibility, don't "close" our objects. There are
		// many fields that are not currently represented. Setting this to
		// false, the default and recommended value, will break many existing
		// installs. TestTemplate will catch many of these breakages.
		AllowAdditionalProperties: true,

		// jsonschema, by default, will rely on omitempty flags to determine if
		// a value is required or not. This has too much of an impact on how
		// the underlying JSON is shaped and marshalled/unmarshalled. Instead,
		// rely on explicitly set required tags.
		RequiredFromJSONSchemaTags: true,

		// Builtin Kubernetes types can generate a JSON schema but it's a built
		// difficult to do so as all the information is stored in kubebuilder
		// annotations. For now, we'll hard code any types that need to be
		// enhanced.
		Mapper: func(t reflect.Type) *jsonschema.Schema {
			switch reflect.New(t).Interface().(type) {
			case *intstr.IntOrString:
				return &jsonschema.Schema{
					OneOf: []*jsonschema.Schema{
						{Type: "string"},
						{Type: "number"},
					},
				}
			case *corev1.PodFSGroupChangePolicy:
				return &jsonschema.Schema{
					Type: "string",
					Enum: []any{
						corev1.FSGroupChangeOnRootMismatch,
						corev1.FSGroupChangeAlways,
					},
				}
			case monitoringv1.Duration:
				return &jsonschema.Schema{
					Type:    "string",
					Pattern: "^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$",
				}
			case *resource.Quantity:
				return &jsonschema.Schema{
					OneOf: []*jsonschema.Schema{
						{Type: "integer"},
						{Type: "string", Pattern: "^[0-9]+(\\.[0-9]){0,1}(m|k|M|G|T|P|Ki|Mi|Gi|Ti|Pi)?$"},
					},
				}
			default:
				return nil
			}
		},
	}

	if len(os.Args) != 2 {
		fmt.Printf("Wrong number of arguments %d, require 2\nusage: %s <redpanda|operator>\n", len(os.Args), os.Args[0])
		os.Exit(1)
	}

	val, exist := schemas[os.Args[1]]
	if !exist {
		fmt.Printf("schema %s does not exist\nusage: %s <redpanda|operator>\n", os.Args[1], os.Args[0])
		os.Exit(1)
	}

	schema := r.Reflect(val)
	makeArrayNullableRecursive(schema)

	// Leave a note to dissuade any would be manual editors.
	schema.Description = "DO NOT EDIT!. This file was generated by ./cmd/genschema/genschema.go"

	// Because of jsonschema's usage of an ordered map, the key ordering is a
	// bit strange. Round trip through an untyped map[string]any to have go
	// sort the keys alphabetically. (This helps reduce diff churn).
	untyped := Must(valuesutil.UnmarshalInto[any](schema))
	data := Must(json.MarshalIndent(untyped, "", "  "))

	fmt.Printf("%s\n", data)
}

func makeArrayNullableRecursive(schema *jsonschema.Schema) {
	for pair := schema.Properties.Oldest(); pair != nil; pair = pair.Next() {
		if pair.Value.Type == "array" {
			schema.Properties.Set(pair.Key, &jsonschema.Schema{
				OneOf: []*jsonschema.Schema{
					pair.Value,
					{Type: "null"},
				},
			})
		}
		makeArrayNullableRecursive(pair.Value)
	}
}
