# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
tls:
  enabled: true
  certs:
    # in the future we want to also add the
    default:
      caEnabled: true
    external:
      secretRef:
        name: external-tls-secret
      caEnabled: true

external:
  enabled: true
  type: NodePort
  domain: random-domain

listeners:
  # NOT including admin-api listeners because it only has one and it is using internal
  # tls certs by default.
  # -- Kafka API listeners.
  kafka:
    # -- The port for internal client connections.
    port: 9093
    tls:
      # Optional flag to override the global TLS enabled flag.
      # enabled: true
      cert: default
      requireClientAuth: false
    external:
      default:
        # enabled: true
        # -- The port used for external client connections.
        port: 9094
        # -- If undefined, `listeners.kafka.external.default.port` is used.
        advertisedPorts:
          - 30090
        tls:
          # enabled: true
          cert: external
  # -- Schema registry listeners.
  schemaRegistry:
    enabled: true
    port: 8081
    kafkaEndpoint: default
    tls:
      # Optional flag to override the global TLS enabled flag.
      # enabled: true
      cert: default
      requireClientAuth: false
    external:
      default:
        # enabled: true
        port: 8084
        advertisedPorts:
          - 30080
        tls:
          # enabled: true
          cert: external
  # -- HTTP API listeners (aka PandaProxy).
  http:
    enabled: true
    port: 8082
    kafkaEndpoint: default
    tls:
      # Optional flag to override the global TLS enabled flag.
      # enabled: true
      cert: default
      requireClientAuth: false
    external:
      default:
        # enabled: true
        port: 8083
        advertisedPorts:
          - 30070
        tls:
          # enabled: true
          cert: external
