statefulset:
  # Deprecated field. Do not copy or you'll get coal for Christmas.
  podSecurityContext:
    runAsUser: 1111
    runAsGroup: 2222
    fsGroup: 3333
    fsGroupChangePolicy: "OnRootMismatch"

  securityContext:
    runAsUser: 4444
    runAsGroup: 5555
    fsGroup: 6666
    fsGroupChangePolicy: "OnRootMismatch"

  sideCars:
    configWatcher:
      securityContext:
        runAsGroup: 7777
        runAsUser: 8888
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: false
    controllers:
      enabled: true
      securityContext:
        runAsGroup: 1234
        runAsUser: 5678
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: false

rbac:
  enabled: true
