# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Lint and Test Connectors Chart

on:
  pull_request:
    branches:
      - "**"
    paths:
      - .github/*.sh
      - .github/ct-connectors.yaml
      - .github/kind.yaml
      - .github/workflows/pull_requests_connectors.yaml
      - charts/**
      - 'charts/connectors/**'
      - '!charts/console/**'
      - '!charts/kminion/**'
      - '!charts/operator/**'
      - '!charts/redpanda/**'
      - '!**/*.md'

defaults:
  run:
    shell: nix develop --impure --command bash {0}

jobs:
  lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash {0} # Explicit restore the default for jobs not using nix.
    steps:
      - name: Noop
        run: echo noop

  version-and-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout main
          git checkout -

      - name: Run CI file name checker
        run: .github/check-ci-files.sh charts/connectors/ci

      - name: Connectors lint
        run: ct lint --config .github/ct-connectors.yaml --github-groups

  check-values:
    runs-on: ubuntu-22.04
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout main
          git checkout -

      - name: compare connectors values with main
        run: dyff --color=off -k between -s <(git show 'origin/main:charts/connectors/values.yaml') charts/connectors/values.yaml

  test:
    needs: lint
    name: Run ct tests for connectors chart
    strategy:
      fail-fast: true
    runs-on: ubuntu-22.04
    steps:
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout main
          git checkout -

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --config .github/ct-connectors.yaml)
          echo $changed
          if [[ -n "$changed" ]]; then
            echo changed="true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          config: .github/kind.yaml

      - name: Check kind config worked
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl get nodes

      - name: install cert-manager
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          task helm:install:cert-manager

      - name: install Redpanda
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm dependency build charts/redpanda
          helm install --namespace redpanda --create-namespace redpanda charts/redpanda --wait --wait-for-jobs \
            --set connectors.enabled=false

      - name: Copy Redpanda tls cert to connectors chart
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl -n redpanda wait --for=condition=Ready --timeout=10m certificates/redpanda-default-cert
          mkdir -p charts/connectors/templates/hidden-only-for-ci
          kubectl -n redpanda get secret -o yaml redpanda-default-cert | \
            sed -e '/namespace/d' | \
            sed -e '/resourceVersion/d' | \
            sed -e '/uid/d'  > charts/connectors/templates/hidden-only-for-ci/redpanda-tls.yaml

      - name: Run chart-testing (install and upgrade)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install \
            --github-groups \
            --upgrade \
            --config .github/ct-connectors.yaml \
            --skip-missing-values \
            --target-branch ${{ github.event.repository.default_branch }}
  summary:
    if: always()
    needs:
      - test
    runs-on: ubuntu-22.04
    steps:
      - name: Summarize the results of the test matrix pass/fail
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs)}}
