---
name: Test Redpanda Chart
on:
  workflow_call:
    inputs: {}
    secrets: {}
defaults:
  run:
    shell: nix develop --impure --command bash {0}
jobs:
  test-redpanda:
    name: "${{ matrix.version }}/${{ matrix.testvaluespattern }}: Run ct tests"
    strategy:
      matrix:
        version:
          # See also: https://redpandadata.atlassian.net/wiki/spaces/CORE/pages/16711857/Releases+Backports
          - v23.3.20
          - v24.1.15
          - "" # Test the default / Most recent version of Redpanda.
        testvaluespattern:
          - '0[1-3]*'
          - '0[4-6]*'
          - '0[7-9]*'
          - '1[0-1]*'
          - '12*'
          - '13*'
          - '14*'
          - '15*'
          - '1[6-7]*'
          - '18*'
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # Cache the nix store.
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      # Cache helm repositories.
      - uses: actions/cache@v4
        with:
          key: helm-repositories
          path: |
            ~/.cache/helm
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # we're excluding console from testing until we have a way to test it with Redpanda
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --config .github/ct-redpanda.yaml)
          echo "$changed"
          if [[ -n "$changed" ]]; then
            echo changed="true" >> "$GITHUB_OUTPUT"
          fi
      - name: Set up for matrix
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          echo bash -O extglob -c "rm -v charts/redpanda/ci/!(${{ matrix.testvaluespattern }})"
          bash -O extglob -c "rm -v charts/redpanda/ci/!(${{ matrix.testvaluespattern }})"
      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde  # v1.10.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          config: .github/kind.yaml
      - name: Check kind config worked
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl get nodes
      - name: Annotate nodes for rack awareness
        if: steps.list-changed.outputs.changed == 'true'
        run: .github/annotate_kind_nodes.sh chart-testing
        # ===== Required Test Files === start
      - name: Create tls helm templates
        if: steps.list-changed.outputs.changed == 'true'
        run: .github/create_tls.sh "random-domain"
      - name: Create sasl secret templates
        if: steps.list-changed.outputs.changed == 'true'
        run: .github/create-sasl-secret.sh "some-users"
      - name: Move files to redpanda template dir
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          mv external-tls-secret.yaml charts/redpanda/templates/
          cp .github/external-service.yaml charts/redpanda/templates/
          mv some-users-updated.yaml charts/redpanda/templates/
        # ===== Required Test Files === end
      - name: Install cert-manager
        if: steps.list-changed.outputs.changed == 'true'
        run: task helm:install:cert-manager
      - name: Install prometheus-operator
        if: steps.list-changed.outputs.changed == 'true'
        run: task helm:install:kube-prometheus-stack
      - name: Install metallb
        if: steps.list-changed.outputs.changed == 'true'
        run: task helm:install:metallb
        # Chart-testing requires there to be a branch on the local repository
        # for diffing. This will create such a branch without performing a
        # checkout.
      - name: Fetch origin/main
        if: steps.list-changed.outputs.changed == 'true'
        run: git fetch origin ${{ github.event.repository.default_branch }}:${{ github.event.repository.default_branch }}
      - name: Run chart-testing (install and upgrade)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install \
            --github-groups \
            --upgrade \
            --config .github/ct-redpanda.yaml \
            --helm-extra-set-args="--set=image.tag=${{ matrix.version }}" \
            --skip-missing-values \
            --chart-dirs=charts/redpanda \
            --target-branch ${{ github.event.repository.default_branch }}
